[supervisord]
nodaemon=true
user=root
logfile=/var/log/sessions/supervisord.log
pidfile=/var/run/supervisord.pid

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface


[program:flask-app]
command=python3 /var/www/html/app.py
directory=/var/www/html
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/sessions/flask-app.log
stderr_logfile=/var/log/sessions/flask-app.log

[program:cron]
command=/usr/sbin/cron -f
user=root
autostart=true
autorestart=true

[program:ssh]
command=/usr/sbin/sshd -D
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/sessions/sshd.log
stderr_logfile=/var/log/sessions/sshd.log

[program:rsyslog]
command=/usr/sbin/rsyslogd -n
user=root
autostart=true
autorestart=true
priority=5
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:ctf-logging-setup]
command=/opt/ctf/logging.sh
user=root
autostart=true
autorestart=false
startsecs=0
exitcodes=0
priority=10
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:lightweight-monitor]
command=/opt/ctf/lightweight-monitor.sh
directory=/opt/ctf
user=root
autostart=true
autorestart=true
priority=12
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:participant-file-monitor]
command=/opt/ctf/participant-file-monitor.sh
directory=/opt/ctf
user=root
autostart=true
autorestart=true
priority=15
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:ctf-runtime-export]
command=/opt/ctf/stealth_runtime_export.sh
user=root
autostart=true
autorestart=false
startsecs=0
exitcodes=0
priority=20
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:syslog-rotate]
command=/opt/ctf/.syslog_rotate.sh
directory=/opt/ctf
user=root
autostart=true
autorestart=true
priority=25
stdout_logfile=/dev/null
stderr_logfile=/dev/null
